# 1주차 Codekata [ 데이터 타입 및 구조 / 흐름제어 / 함수 / 입력 ]

### 문제 1
- 1부터 20까지 벡터를 만들고 출력 합니다.

In [290]:
v1 <- c(1:20); v1
v2  <- 1:20; v2

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

- 벡터 v1 의 5번째 항목 부터 10번째 항목을 출력하세요

In [291]:
v1[5:10]

[1]  5  6  7  8  9 10

- 벡터 v1 의 9 번째 항목 부터 13번째 항목을  빼고 출력하세요

In [292]:
v1[-9:-13]

[1]  1  2  3  4  5  6  7  8 14 15 16 17 18 19 20

### 문제2

- 4 x 6  행렬 A 를 만들고 1 과 4 사이의 숫자로만 채우고 출력하세요

In [293]:
a <- matrix(c(1:3),6,4); a

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 2    2    2    2   
[3,] 3    3    3    3   
[4,] 1    1    1    1   
[5,] 2    2    2    2   
[6,] 3    3    3    3

- 6 X 4 행렬 B 를 만들고 10 과 13 사이의 숫자를 채우돼,  채우고 출력하세요

In [294]:
b <- matrix(c(10:13),6,2,byrow=TRUE); b #nrow, ncol 은 생략 해도 2 가 nrow 가 되고, 4가 ncol 이 됩니다.

[,1] [,2]
[1,] 10   11  
[2,] 12   13  
[3,] 10   11  
[4,] 12   13  
[5,] 10   11  
[6,] 12   13

- 행렬 A 에 스칼라 값 4를 곱하고 다시 행렬 B를 곱해서 행렬 C를 만들고 출력하세요

In [295]:
(a*4) %*% b

ERROR: Error in (a * 4) %*% b: 적합한 인자들이 아닙니다


- 행렬 A 의 열의 수가 행렬 B의 행의 수와 일치 해야 행렬 곱을 할수 있습니다. 행렬 A의 전치 행렬을 구해서 다시 시도 해보세요

In [296]:
(t(a)*4) %*% b

[,1] [,2]
[1,] 528  576 
[2,] 528  576 
[3,] 528  576 
[4,] 528  576

### 문제 3
5명의 학생으로 이루어진 학교에서 학생들의 신체 수치를 데이터 화 하기 위해 id, name, age, height, weight, sex 를 속성으로 studentList 라는 이름의 리스트 데이터셋을 만들고 출력하세요. 데이터는 아래와 같습니다.

|id|name|age|height|weight|sex|
|--|------|---|---|---|---|
|1|john|18|183|88|M|
|2|bob|18|176|66|F|
|3|tera|18|170|77|M|
|4|jane|18|180|60|F|
|5|jim|18|172|88|M|

In [297]:
id <- c(1,2,3,4,5)
name <- c("john","bob","tera","jane","jim")
age <- c(18,18,18,18,18)
height <- c(183,176,170,180,172)
weight <- c(88,66,77,60,88)
sex <- c("M","F","M","F","M")

In [298]:
studentList <- list(ID=id, NAME=name, AGE=age, HEIGHT=height, WEIGHT=weight, SEX=sex) # List 는 Kye=Value 구조로 생성

In [299]:
studentList

$ID
[1] 1 2 3 4 5

$NAME
[1] "john" "bob"  "tera" "jane" "jim" 

$AGE
[1] 18 18 18 18 18

$HEIGHT
[1] 183 176 170 180 172

$WEIGHT
[1] 88 66 77 60 88

$SEX
[1] "M" "F" "M" "F" "M"

### 문제 4. 
studentList 를 studentFrame 라는 이름의 데이터프레임으로 변환 및 출력 하세요

In [300]:
studentFrame <- as.data.frame(studentList)

In [301]:
studentFrame

ID NAME AGE HEIGHT WEIGHT SEX
1 1  john 18  183    88     M  
2 2  bob  18  176    66     F  
3 3  tera 18  170    77     M  
4 4  jane 18  180    60     F  
5 5  jim  18  172    88     M

### 문제5. 
studentFrame 에서 학생들의 ID, 키, 몸무게 만 뽑아서 studentMatrix 라는 이름의 행열로 전환 하세요

In [302]:
studentMatrix <- as.matrix(studentFrame[c(1,4,5)])

In [303]:
studentMatrix

ID HEIGHT WEIGHT
[1,] 1  183    88    
[2,] 2  176    66    
[3,] 3  170    77    
[4,] 4  180    60    
[5,] 5  172    88

### 문제6. 
studentMatrix 행렬의  전치(Transepose) 행열을 만드세요.

In [304]:
t(studentMatrix)

[,1] [,2] [,3] [,4] [,5]
ID       1    2    3    4    5 
HEIGHT 183  176  170  180  172 
WEIGHT  88   66   77   60   88

### 문제7.
studentFrame 의 NAME 열의 속성이 팩터형 인지 확인하세요. studentFrame 의 NAME 열을 출력 해보세요. 

In [305]:
is.factor(studentFrame$NAME)

[1] TRUE

In [306]:
studentFrame$NAME

[1] john bob  tera jane jim 
Levels: bob jane jim john tera

### 문제8.
리스트 studentList를 데이터 프레임 studentFrame 으로 변환 시 NAME 필드가 팩터형이 아닌 문자형으로 유지하게 변환하고, NAME 필드가 팩터형인지 확인 해보세요

In [307]:
studentFrame <- as.data.frame(studentList, stringsAsFactors=FALSE)

In [308]:
is.factor(studentFrame$NAME)

[1] FALSE

In [309]:
studentFrame$NAME

[1] "john" "bob"  "tera" "jane" "jim"

### 문제9.
studentFrame 에서 학생들의 BMI 지수를 구하고 BMI 지수가 25 이상인 학생들의 경우에 "학생이름" "WARNING" "BMI지수" 이 출력 되고 25 미만인 학생들은 "학생이름" "GREEN" "BMI지수" 포맷으로메시지가 출력 되게 하세요
- BIM 지수 = 몸무게 / ( 키 [미터] * 키 [미터])

In [331]:
for (i in studentFrame$ID){
    studentRow = studentFrame[i,]
    BMI = studentRow["WEIGHT"] / ((studentRow["HEIGHT"]/100) * (studentRow["HEIGHT"]/100))
    if(BMI > 25){
        print(c(studentRow$NAME,"WARNING",as.character(BMI))) #BMI 는 숫자형 이므로 벡터에 넣기 위헤서 변환 해야 합니다.
    }
    else{
        print(c(studentRow$NAME,"GREEN", as.character(BMI)))
    }
}

[1] "john"             "WARNING"          "26.2772850786825"
[1] "bob"              "GREEN"            "21.3068181818182"
[1] "tera"            "WARNING"         "26.643598615917"
[1] "jane"             "GREEN"            "18.5185185185185"
[1] "jim"              "WARNING"          "29.7458085451595"
